sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - deps=""

matrix:
  fast_finish: true
  allow_failures:
  include:
    - php: 7.2
    - php: 7.3

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
  - if [ "$PROCESS_VERSION" != "" ]; then composer require symfony/process:${PROCESS_VERSION} --dev --no-update; fi
  - if [ "$deps" = "" ]; then composer install; fi
